Thlumyn/clangen

scripts/screens.py

list kits in allegiance screen

---

scripts/cats.py
scripts/screens.py

- save apps/former apps using semicolons
- med cat apps have mentors now
- former app list doesn't get duplicates

apprentice bugfixes and updates

---

scripts/cats.py

check if mentor exists at all before trying to remove app from mentor's list of apps

bugfix: mentorless apprentice dies

---

main.py

Adds support for scrolling the allegiances and events pages using the scroll wheel. By popular request does NOT touch the scroll to click functionality.

Scroll Wheel support

---

scripts/clan.py
scripts/events.py
scripts/game_essentials.py
scripts/screens.py

Adds the ability to choose what biome your Clan's territory is in. Affects events.

Added basic biome selection feature

---

scripts/clan.py
scripts/screens.py
scripts/world.py

I think I fixed the conflicts?

Map fixes take #2

---

scripts/patrol.py

Added hunting territory check script, changed main hunting events section to only use hunting events if the hunting grounds have prey (or if the map is disabled)

Hunting territory now affects patrols

---

scripts/cats.py
scripts/pelts.py
scripts/sprites.py

Calico2 and several specific colors of rosette, smoke, and ticked were either not appearing in-game or displaying the wrong sprite.

Fixed patterns not ingame/displaying incorrectly

---

scripts/screens.py

which causes the game to crash when the Relationship Screen is opened.

Fixed crucial bug

---

main.py
scripts/buttons.py
scripts/cats.py
scripts/screens.py

Changed primary options for trans cats from "transmasc, transfem, transneu" to "trans male, trans female, nonbinary". If a cat is set to nonbinary, a new button will appear to set the gender to custom text. There is also now the option to change a cat back to being cis.

Reworked gender system

---

README.md
main.py
scripts/buttons.py
scripts/game_essentials.py
scripts/screens.py

Options page now has tabs, inspired by how the Make Clan screen is split up into phases.

Reworked options page

---

scripts/patrol.py
scripts/screens.py

* Attempts addressing #71 by splitting list contents with commas. Also removes duplicates from the list so they only appear once.
* Attempts addressing #72 by grouping certain patrol events into conversation patrols.
* Changes ids of some patrols events that had duplicate ids.

Minor patrol changes

---

main.py
requirements.txt
scripts/buttons.py
scripts/game_essentials.py
scripts/screens.py
scripts/sprites.py
scripts/world.py

This PR performs some minor optimizations.
Also removes the pandas dependency because using pandas just for .csv writing felt a bit overkill.

Minor Optimizations

---

scripts/screens.py

checks if a cats age/the clan's age == 1 moon, if yes, text shows as "1 moon" and not "1 moons"

change text to not say "1 moons"

---

scripts/cats.py

Reorganized the thoughts to be alphabetical so it's easier to read. I also made it so certain thoughts are restricted to certain traits, skills, or ages. I also edited words like "twoleg" "clan" "starclan" etc to follow the grammar convention of the books. (twoleg -> Twoleg, clan -> Clan, etc.)

Reorganization of thoughts

---

scripts/patrol.py

changing clan -> Clan, twoleg -> Twoleg

continued grammar convention etc etc

---

scripts/screens.py

continuation of grammar convention

---

scripts/events.py

dont let me make 3 prs at 10pm

typo from my last pr part 2 electric boogaloo

---

scripts/cats.py
scripts/game_essentials.py
scripts/relationship.py
scripts/screens.py

And some bug fixing and screen changes (separated relation themed settings with game settings)

New settings for relationships

---

scripts/cats.py
scripts/game_essentials.py
scripts/relationship.py
scripts/screens.py

Tested: 
- new clan creation
- rush skipped 100 moons (with new clan)
- rush skipped 50 moons (with older clan)

Added relation setting + bug fix

---

scripts/buttons.py
scripts/screens.py
scripts/sprites.py
scripts/text.py

Docstrings for some functions inside classes in text.py, sprites.py, screens.py, and buttons.py. Removes some functions that aren't used anywhere.
May not be fully accurate.

Some docstrings

---

scripts/cats.py

The calico/tortie self.pelt.colour for some reason likes to shapeshift, I've made a temporary solution to have the pelt color remain the same, but the base problem persists. Should be checked out in the future

calico/tortie 'fix'

---

scripts/cats.py
scripts/relationship.py
scripts/screens.py

**Tested:**
- looked at choose_mate_screen to check if age is correct
- looked at choose_mate_screen to check if cat had no mate
- check which cats could possibly have love interactions - checked age (and randomly relation; ~ 100 moons)
- checked uncle/aunt relation (~ 30 moons)

Fix mate bugs

---

scripts/buttons.py
scripts/events.py

Fixes:
* Getting reports of exiles dying multiple times
* Exiling deputies crashing the game

fix: Exile bugs

---

scripts/events.py
scripts/game_essentials.py
scripts/screens.py

Game was saving every frame after the save button was being clicked. This should make it so that the game only saves once. 
It should have the same behaviour with how the "Saved" text appears, though this should probably be changed in the future.

fix: Save lag

---

scripts/cats.py
scripts/events.py
scripts/pelts.py
scripts/sprites.py

Categorized white patches for easier future additions
Added full white into the possibilities
*Fully tested, no bugs found

white patches fixes

---

requirements.txt
scripts/cats.py

Uses the ujson library for faster json operations. This is a new dependency so users will have to reinstall from `requirements.txt`.

perf: Faster saving

---

scripts/scripts/cats.py
scripts/scripts/events.py
scripts/scripts/pelts.py

a couple more white patches tweaks
tried my best to make the accessory events grammatically correct *Tested, no bugs found

a few more fixes

---

scripts/cats.py
scripts/patrol.py

Fixes:
* Certain patrols causing crashes.
* Certain white patches causing crashes.

fix: Some crashes

---

scripts/relation_events.py
scripts/screens.py

Bugfix: kitten interact with exiled cats in relationship events (like they bump into the exiled cat at the border)

Contend: add uncle / aunt as 'related' in relationship screen

---

scripts/cats.py
scripts/events.py

Upon aging up to adolescent, cats can now choose to become a medicine cat instead of a warrior.  Chances of cats choosing med cat will be higher if the current med cat is an elder or if the cat possessed certain kit traits.

New Feature: Autonomous Med Cat Apprentices

---

resources/dicts/conditions/Illnesses.json
resources/dicts/conditions/Injuries.json
resources/dicts/thoughts/family.json
scripts/cat/cats.py
scripts/cat/thoughts.py
scripts/cat_relations/relation_events.py
scripts/conditions.py
scripts/events.py
scripts/game_structure/load_cat.py
scripts/patrol.py
scripts/utility.py
tests/test_conditions.py
tests/test_patrol.py
tests/test_thoughts.py

**Other Content:**
- added base classes and functions for injuries and illnesses **BUT NO INTEGRATION**
**Bugfixes:**
- An adopted kit per event, doesn't list the cat as parent who adopted them
- Loners that join at apprentice age are shown as warriors
- Deputy won't retire upon becoming an elder
- readded the disaster patrols

Content: Added family thoughts

---

scripts/cat_relations/relation_events.py
scripts/clan.py
scripts/events.py
scripts/game_structure/game_essentials.py
scripts/screens/organizational_screens.py
tests/test_relation_events.py

**Added pregnancy function:** 
- Cat will announce the pregnancy
- Cat will guess how many kits they will have
- then the cat will have kits
**Information:** 
The pregnancy will also work for same-sex couples if the setting is turned on. The only one, which will not trigger a pregnancy action is a single male tom. This cat will bring a litter back to the camp. 
The pregnancy is saved in an own folder "pregnancy", with this you can save, close and open the clan again and the pregnancy is still there.

Content: Added Pregnancy

---

scripts/events.py
scripts/screens/cat_screens.py

- fixed trans cats gender not showing properly
- fixed issue where leaders wouldn't lose lives when murdered
- added a fail to the murder event for if the leader has 7 or more lives left and they murder their would-be murderer instead
- fixed kits being killed in border skirmishes

various bugfixes

---

scripts/cat_relations/relation_events.py
scripts/events.py
scripts/screens/event_screens.py

- kits with an unknown parent can now have the outsider roots or half-clan backstory
- fixed various things

content: added ability for kits born in clan to have different backstories

---

scripts/cat_relations/relation_events.py
scripts/screens/cat_screens.py

& disgraced backstory glitching

bugfix: halfclan backstories not showing up properly

---

scripts/cat/cats.py
scripts/cat_relations/relation_events.py

Hopefully this is equivalent to the previous code, but decently faster. All tests pass:
```
----------------------------------------------------------------------
Ran 60 tests in 0.016s
OK
```
Main changes:
- Get cat ID via itertools instead of randint.
- In is_potential_mate, first check if cats have parents/sibs that necessitate the full range of checks.
- Replace instances of random.randint in relationship_checks.py with random.random.
Minor changes:
- Replaced handle_relationships loop with itertools.repeat loop, slightly faster since the iterator is not used. 
- Commented out cat relationships shuffle in handle_relationships.
- Rewrote get_parents to return parents without intermediately appending them to a list. 
- Rewrote is_grandparent to iterate through parents instead of …

Apply some optimizations to relationship events and cats

---

scripts/events.py

- Rewrite disaster string handling to iterate
- Amount of dead cats is decided via random.choices
- Replaced randint with random.getrandbits
- Decide if a disaster is actually going to happen before running any other code

Rewrite disaster string handling + chance (+ misc. indentation & randint --> random.random)

---

scripts/cat/cats.py

Sets out of range cats to always be elders in the Cat class \_\_init__

Fix failure to load save if cat is older than 300 moons

---

scripts/cat/cats.py

fix 0 moons causing kits to age up

---

scripts/events.py
scripts/game_structure/buttons.py
scripts/game_structure/game_essentials.py
scripts/screens/organizational_screens.py

as of right now it randomly chooses a warrior who has trained an apprentice
in the future it can possibly prioritize experience, trust from the leader, age, etc.

Add toggle to auto choose deputy

---

scripts/cat/cats.py

Bugfix for a List Index crash that I didn't catch in my previous PR.

Bugfix: List Index crash

---

scripts/events.py

Also fuses the disaster strings

Reduce base scar chance and reduce the amount of cats killed in extinction events

---

scripts/clan.py
scripts/events.py
scripts/game_structure/buttons.py
scripts/screens/event_screens.py

temporary open/close borders feature
closed borders mean no outsiders are allowed to join the clan
in the future, I believe there were mentions of having antagonize play a role in the number of outsiders joining

Open/Close Borders feature

---

requirements.txt
scripts/clan.py
scripts/events.py
scripts/patrol.py
scripts/screens.py

- commented out exile
- commented out map
- commented out Cats Outside The Clan
- removed numpy and noise from requirements
- fixed wars and clan relations junk

other/bugfixes: commented out unfinished features & fixed wars
