.github/workflows/main.yml
.gitignore
Clangen.spec
main.py

Made changes so that Clangen works more robustly on MacOS.
- File path is now dynamic so Clangen can be installed in folders other than `/Applications`.
- Fixed a bug with the MacOS CI build that prevented the automatic build from launching.
- Made changes to the MacOS CI build that make launching the game much faster with the trade-off of making the filesize larger.

Mac support fixes

---

scripts/screens.py

The background file was being loaded every frame and causing a significant performance hit on the Starclan screen. This makes it so that the background file is only loaded once, when the screen initializes.

Starclan Screen Performance Improvement

---

scripts/patrol.py

ozzie ☁#2473 in #dev-bug-reports pointed out that apprentices could be chosen as patrol leaders even if they were not the most experienced cat, so now when creating a patrol, each cat will be checked if their status is apprentice or not. If not, they are added to list possible_patrol_leaders and a patrol leader is picked from that. If the patrol only contains apprentices, it will pick a random apprentice to be the leader

Apprentices are not patrol leaders unless patrol is only apprentices

---

main.py
scripts/screens.py

* Same as #99 but for the start screen.
* Only gets the map when navigating to the map screen instead of every frame.
* Limits allowed input events for pygame.

Optimizing start screen, input

---

scripts/buttons.py

Previously, as mentioned in issue #102, changing a kit or apprentice name to one with the same kit/paw suffix overwrote the hidden suffix, meaning they would remain kit or paw even when growing up. This change keeps the hidden suffix unchanged if the new suffix matches the current special status.

Name change bugfix

---

scripts/cats.py
scripts/screens.py

Should fix: 
* Mating dead cats
* Mating exiled cats
* Crash on non-Windows OS
* Constant affairs all the time
It should also make the list of mates (when manually assigning) more consistent with what kind of cats can get chosen to randomly be mated.

More mate fixes

---

scripts/patrol.py

Fixes an issue where certain events would make experience values would go over 80 and break a cat's save.

fix: Experience values corrupting saves

---

scripts/cats.py

JSON save files weren't indented so they were hard to read.

style: Indents in saves

---

main.py
scripts/cats.py
scripts/events.py

The fix for resources not found was already in place, but for Mac only. I took out the Mac-only if, which I think should be fine (it fixed it for me on Windows).
The other fix isn't a bug I've actually seen, but if somehow the number of cats was 2 or less, the countdowns would be initialized to 0 and then get stuck in the while loop. So check if it's <=0 instead of ==0.

Bugfix: resources not found and countdown init to 0

---

scripts/buttons.py

Cats were automatically saving when changing name, changing gender, and choosing apprentices. This caused lag because saving is slow. This PR removes this auto saving. 
The game probably shouldn't be saved in these places anyway because it's unintuitive for users.

other: Auto save less often

---

scripts/events.py
scripts/patrol.py

Bugfix: extinction event where an enemy clan kills your cats was not pulling from the list of neighboring clans
content: 'abandoned kit' patrol can now give kittypet kits with a collar chance.  new patrol added that can invite a loner med cat into the clan.

Bugfixes and Content: Patrols and Events

---

scripts/patrol.py
scripts/screens.py

Patrol event text now replaces "Your patrol" and "The patrol" with the cat's name if the cat is on a solo patrol.
Made other small adjustments, mostly fixing formatting to be consistent across patrol events.  Also adjusted the deathberries event to only happen to apprentices and to have a "good" variant with strawberries.  Suspicious pawprints event also has a scar outcome now.

Content/Fixes: Patrol Adjustments

---

scripts/cats.py
scripts/events.py

bugfix: enemy clan name was causing an error with specific extinction event
Content: 
Upon aging up from kit > app and app > adult and adult > elder the cat has a chance to change their trait for either: a new trait from the same personality group, a new trait picked randomly from the full trait pool, or to keep their original trait.  Kit traits will always change to an 'adult' trait, but the trait has a higher chance of pulling from the same personality group as their original trait. 
Elders now have a unique skill pool that they pull from when aging up to elder (or when spawning if spawning as elder).  They have unique thought pools to pull from according to skill.  Leaders and Meds are exempt from this skill change.

Content and Bugfixes: Trait switches and Elder skills

---

scripts/cats.py

Experience when loading was set after the experience levels were set, so internally the experience would be correct, but the level would be displayed as wrong. This fixes that issue by just setting experience levels whenever experience is changed.

fix: Changing exp bug

---

scripts/events.py
scripts/relation_events.py
scripts/screens.py

Fixes some crashes relating to moon skips. More specifically: 
* `TypeError: builtin_function_or_method object is not iterable` - Root cause still not found, but this should prevent the crash. Hopefully. 
* Occasional infinite loading on moonskip 
* Crash when a cat in an interaction event can't find anybody else to interact with.

Fix: Various moon skip crashes

---

scripts/cats.py

Cats missing relationship files (e.g. custom cats, cats imported through the save converter) wouldn't have any relationships at all. This gives them a relationship with the clan if there's no relationship file to read.

fix: Cats missing relationships

---

scripts/relationship.py

Was only checking one cat for valid mate events. Should check both cats. Bug was fixed in experimental but it should be fixed in release too.

fix: Invalid mates being set

---

resources/dicts/patrols/general.json
resources/dicts/patrols/general_new_cat.json
resources/dicts/patrols/leaves/greenleaf.json
resources/dicts/patrols/leaves/leaf-fall.json
scripts/cat/cats.py
scripts/events.py
scripts/patrol.py
scripts/screens/event_screens.py

Trait Switching: cats weren't switching traits and were taking kit traits again, bug now fixed
Missing Patrols: Med cat loner and abandoned kit patrols were missing, added them back in
Mass Extinction Events: Kits no longer die in battle disaster events or other events that didn't make sense
Various typos in patrols fixed

Bugfixes: Trait Switching - Missing patrols - Typos

---

scripts/screens/cat_screens.py
scripts/screens/clan_creation_screens.py
scripts/screens/clan_screens.py

Changes a few instances of ``biome.lower()``, which just returns the variable, to actually change the variable with ``biome = biome.lower()``.
Currently, the game crashes on case-sensitive filesystems whenever it tries to load a resource from ``resources/images/camp_bg``:
```
Traceback (most recent call last):
File "/home/user/clangen/main.py", line 266, in <module>
game.all_screens[game.current_screen].on_use()
File "/home/user/clangen/scripts/screens/clan_creation_screens.py", line 715, in on_use
self.sixth_phase()
File "/home/user/clangen/scripts/screens/clan_creation_screens.py", line 561, in sixth_phase
self.choose_camp()
File "/home/user/clangen/scripts/screens/clan_creation_screens.py", line 590, in choose_camp
self.camp_art()
File …
```

Fix biome path not actually getting converted to lowercase.

---

scripts/clan.py

status_change() rerolls traits for medicine cats. It shouldn't be called when loading saves unless it has to be.

fix: Med cats changing traits

---

main.py
scripts/cat/appearance_utility.py
scripts/cat/cats.py
scripts/cat/names.py
scripts/cat/pelts.py
scripts/cat/sprites.py
scripts/cat/thoughts.py
scripts/cat_relations/relation_events.py
scripts/cat_relations/relationship.py
scripts/clan.py
scripts/conditions.py
scripts/events.py
scripts/game_structure/buttons.py
scripts/game_structure/game_essentials.py
scripts/game_structure/load_cat.py
scripts/game_structure/text.py
scripts/patrol.py
scripts/screens/base_screens.py
scripts/screens/cat_screens.py
scripts/screens/clan_screens.py
scripts/screens/relation_screens.py
tests/test_cat.py

Tested the exp. branch with a few linters & tried to apply a few of the more straightforward fixes/optimizations, should've maybe split this up into multiple commits & pulls... :"3
This doesn't apply any style-related changes as to not exacerbate possible merge conflicts with other forks.
(+0.18 with pylint)
Addition:
- Added python3 shebang to main.py
Fixes:
- Fixed 'NOTAIL' not causing 'HALFTAIL' to be set to None because `cat.specialty == None` was used instead of an assignment.
- Renamed second test_adult function to test_senior_adult to avoid redefinition
Pylint recommendations:
- Removed unused ujson import from `clangen/scripts/conditions.py`
- Removed object inherits, which are already implictly inherited in Python 3. Presumably this is a leftover from Python 2? (pylint …

Apply some basic pylint-recommended optimizations ( + 2 minor fixes & a py3 shebang )

---

scripts/events.py
scripts/screens/cat_screens.py

- fixed the bug where disgraced leader and disgraced deputy kept switching
- fixed the loner event so that it actually shows the correct event when they change their name or don't

bugfixes: backstories changing and loner name events not being correct

---

scripts/cat/cats.py
scripts/screens/base_screens.py
scripts/screens/cat_screens.py
scripts/screens/patrol_screens.py
scripts/screens/relation_screens.py

Bugfix: adding additional checks to make certain the button is available when no deputy is present
Bugfix: fixed the +1 button disappearing if only one able cat was left
Bugfix: If you selected a cat on the Choose Mates screen and then hit the next/prev cat buttons, the selected cat would not be reset.  This caused a crash if you continued hitting next/prev till you reached the Choose Mate screen of the selected cat, causing it to try and show the cat as it's own potential mate.
Bugfix:  If you switched an 6 moon apprentice from warrior app to med app then they would still be listed on the Former App list of their old mentor.
Less a bugfix, and more a temporary solution:  The patrol screen displays and allows you to directly select a mentor's apprentice.  However, it only displays the …

Bugfix: Deputy Promotion button , +1 button, ect

---

scripts/game_structure/buttons.py
scripts/game_structure/image_cache.py
scripts/screens/base_screens.py
scripts/screens/cat_screens.py
scripts/screens/clan_creation_screens.py
scripts/screens/event_screens.py
scripts/screens/organizational_screens.py
scripts/screens/patrol_screens.py
scripts/screens/relation_screens.py
scripts/screens/world_screens.py

A few image optimizations to go with the UI update: 
* Creates a new module `image_cache` that implements a really simple dictionary caching function for loading images, and calls it on images that are loaded every frame. My justification for making it a function in a module rather than a class is that I don't think there's a use for multiple image caches in this project so having it easily imported makes it easier to use.
* Runs `convert_alpha()` on some surfaces that didn't have it. This just makes blitting the surfaces a bit faster.

perf: Quick image optimizations

---

scripts/screens/patrol_screens.py

clicking on a cat with an apprentice (while viewing the patrol screen) would crash the game,  it's now fixed

Bugfix: patrol screen mentor crash

---

resources/dicts/patrols/general_fighting.json

i just noticed the second patrol event on this page had an accidental extra word in it

bugfix: typo

---

scripts/patrol.py
scripts/screens/cat_screens.py

Deathberry event ID wasn't in the list of patrols that kill, it was also the same as the ID for the Strawberry event (a variant of the deathberry.) ID is now in the right spot.
Trans button was showing incorrect gender if the cat's gender was switching using specify gender screen (so you could set a female cat as 'male' and then the trans button would be 'switch to trans female')

Bugfix: Deathberry event, Trans button

---

scripts/cat/cats.py
scripts/screens/cat_screens.py

More grammar adjustments for History tab.
I had missed a few things when trying to adjust how Reserved vs Abrasive was recorded in my previous PR, this actually fixes the problem and stops the game from crashing.

Bugfix: Grammar and Trait Choosing Crash

---

tests/test_cat.py
tests/test_relation_events.py

Ran the tests through teyit since the Python 3.12 changelog recommends it, apparently it's slated to remove some depreciated unittest features. Don't think any of those were present here though, so this is mostly just convention stuff.
```
assertTrue               => assertEqual               refactoring happened 1 times.
assertFalse              => assertNotIn               refactoring happened 1 times.
assertTrue               => assertNotEqual            refactoring happened 2 times.
assertTrue               => assertIn                  refactoring happened 3 times.
assertTrue               => assertLess                refactoring happened 6 times.
assertTrue               => assertGreater             refactoring happened 6 times.
assertTrue               => assertLessEqual …
```

Reformat tests (with teyit)

---

.github/workflows/build.yml

Seems like the macOS build doesn't work with Python 3.11 + pygame 2.1.3. Few ppl in on the discord had this issue and it doesn't run for me on a vm either, not sure why exactly. Probably best to just roll it back for now.

Revert MacOS build to Python 3.10 & pygame 2.1.2

---

.github/workflows/build.yml

- Fixes win10+ zip not being included in releases because it had the wrong name
- Makes the tar.exe release zip only build when a tag is pushed
- Fixes the extension for the win32/64 artifacts being .zip.zip

Minor fixes for build workflow
